import type { Metadata } from "next";
import "./globals.css";
import {
  Gravitas_One,
  Manrope,
  Playfair_Display,
} from "next/font/google";

const gravitas = Gravitas_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-gravitas",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-manrope",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${gravitas.variable}
          ${manrope.variable}
          ${playfair.variable}
        `}
      >
        {children}
      </body>
    </html>
  );
}
